### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by DivyanshThe-Creator**
Hii,
I Like your repository.
This is very helpful, I like your work.
It is amazing. :100: 
.
.
Hope you like it. :)

### CODE REVIEW

**Comment by pekkaklarck** [comment]
Grammar/type fixes look good but breaking the code examples with them is bad. Are you interested to fix the examples or was this submitted just to get a #hactoberfest t-shirt?

**Comment by DivyanshThe-Creator** [comment]
If you want then I will fix the examples or otherwise, I just get a
#hactoberfest t-shirt.
Thank You🙂🙂

**Comment by pekkaklarck** [comment]
The PR cannot be merged in the current form I could obviously fix it myself, but that's some extra work. If you really want to contribute, please fix the examples so that I could just merge this.

**Comment by DivyanshThe-Creator** [comment]
I am new to Github. I have no any more experience.
This is my first year to get a #Hacktoberfest T-Shirt.
: )

**Comment by DivyanshThe-Creator** [comment]
So, please can you commit the changes.

**Pull request closed without merging**
