### PR TITLE
@keyword decorator features

### PR DESCRIPTION
**Pull request by epronk**
Please review and merge changes for issue #35.
Any feedback is welcome.

Eddy

### CODE REVIEW

**Comment by pekkaklarck** [comment]
Thanks for a great PR! Custom keyword names are handled very well. Few comments:

- Adding support to configure the automatic start-up is a good idea (there's even #22 related to it), but it should be in a separate PR. It should also be documented and tested.

- Handling keyword tags is not tested at all. I think it can only be tested with unit tests.

- The main problem merging this is that I got carried away with other changes (Python 3 support, refactoring, dynamic library support, ...) and as a result there are no conflicts. If you have time and interest to fix the PR yourself after these changes let me know. Because conflicts are totally my mistake and I can fix it too.

**Comment by epronk** [comment]
Thanks for your feedback. I'll try to resolve the conflicts soon.

**Comment by pekkaklarck** [comment]
Great! I'm currently working with a system to allow starting the server on background and this includes configuring the automatic start-up. You can thus exclude that totally and concentrate on `@keyword` support.

**Comment by epronk** [comment]
I'll close this one and send a new one for a different branch.

**Pull request closed without merging**
